export const EVENTS_STRINGS = {
  TITLE: "Events",
  TABLE: {
    TABLE_TITLE: "Events",
    HEADER_ID: "ID",
    HEADER_FULL_NAME: "Full Name",
    HEADER_EVENT_NAME: "Event Name",
    HEADER_EVENT_VENUE: "Eevnt Venue",
    HEADER_STATUS: "Status",
    HEADER_ACTIONS: "Actions",
  },
  FORM: {
    ADD: "Add Event",
    EDIT: "Edit Event",
    FIELD_LABELS: {
      FULL_NAME: "Full Name",
      NAME: "Event Name",
      INDUSTRY_TYPE: "Industry Type",
      COUNTRY: "Country",
      STATE: "State",
      CITY: "City",
      VENUE: "Event Venue",
      LINK: "Event Link",
      LAT: "Latitude",
      LNG: "Longitude",
      GEO_ADDRESS: "Event Geo Address",
      DATE: "Date",
      START_TIME: "Start Time",
      END_TIME: "End Time",
      MODE: "Event Mode",
      TYPE: "Event Type",
      DETAILS: "Event Details",
      BANNER: "Event Banner",
      STATUS: "Status",
      STATUS_ACTIVE: "Active",
      STATUS_INACTIVE: "Inactive",
    },
  },
};
