export const EVENTS_STRINGS = {
  TITLE: "Events",
  TABLE: {
    TABLE_TITLE: "Events",
    HEADER_ID: "ID",
    HEADER_NAME: "Event Name",
    HEADER_VENUE: "Venue",
    HEADER_STATUS: "Status",
    HEADER_ACTIONS: "Actions",
  },
  FORM: {
    ADD: "Add Event",
    EDIT: "Edit Event",
    LABELS: {
      NAME: "Event Name",
      INDUSTRY_TYPE: "Industry Type",
      COUNTRY: "Country",
      STATE: "State",
      CITY: "City",
      VENUE: "Event Venue",
      LINK: "Event Link",
      LAT: "Latitude",
      LNG: "Longitude",
      GEO_ADDRESS: "Geo Address",
      DATE: "Date",
      START_TIME: "Start Time",
      END_TIME: "End Time",
      MODE_ID: "Event Mode",
      TYPE_ID: "Event Type",
      DETAILS: "Event Details",
      STATUS: "Status",
    },
  },
};
