export const INVESTORS_STRINGS = {
  TITLE: "Investors",
  TABLE: {
    TABLE_TITLE: "Investors List",
    HEADER_ID: "ID",
    HEADER_FULL_NAME: "Full Name",
    HEADER_REFERENCE_NO: "Reference No",
    HEADER_NAME: "Name",
    HEADER_APPROVAL_STATUS: "Approval Status",
    HEADER_STATUS: "Status",
    HEADER_ACTIONS: "Actions",
  },
  FORM: {
    ADD: "Add Investor",
    EDIT: "Edit Investor",
    FIELD_LABELS: {
      FULL_NAME: "Full Name",
      USER: "Select Users",
      NAME: "Name",
      COUNTRY: "Country",
      STATE: "State",
      CITY: "City",
      FUND_SIZE: "Fund Size",
      LINKEDIN_URL: "Linkedin URL",
      BIO: "Bio",
      PROFILE_IMAGE: "Profile Image",
      AVAILABILITY: "Availability Status",
      PROFILE: "Profile",
      INVESTMENT_STAGE: "Investment Stage",
      MEETING_CITY: "Meeting City",
      COUNTRIES_TO_INVEST: "Countries to Invest",
      INVESTMENT_INDUSTRY: "Investment Industry",
      LANGUAGE: "Language",
      APPROVAL_STATUS: "Approval Status",
      STATUS: "Status",
    },
  },
};
